spring.application.name=${SPRING_APP_NAME:food_delivery_api}
spring.datasource.url=${DB_CONNECTION_URL:jdbc:postgresql://localhost:5432/java_eats_lite_db}
spring.datasource.username=${DB_USERNAME:java_eats_lite_user}
spring.datasource.password=${DB_PASSWORD:P@ssw0rd}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HiBERNATE_FORMAT_SQL:true}
server.servlet.context-path=/api/v1
